### ISSUE TITLE
layout not displaying correctly

### ISSUE THREAD

**Issue by Dronf3** [katelyynn/bwaa#13]
OS: Windows 10
Browser: Firefox

This has been happening for 3-2 days, it still appears like this after disabling adblock and refreshing many times.
![image](https://github.com/user-attachments/assets/ac26ecf1-1abe-47b7-a16c-6aaa3027bfe8)
![image](https://github.com/user-attachments/assets/2dc50798-e302-4699-9316-9dbbc96adfee)

**Comment by katelyynn** [comment]
most likely due to the latest last.fm update, can fix once im back - sorry for tha inconvenience, meant to update sooner i just got distracted by bleh

**Comment by katelyynn** [comment]
i noticed while testing it crashed for this main reason 99% of the time then i got this weird random crash i cant reproduce, this update is strangely unstable lmao. but this seems to have fixed the main issue
